<?php

/**
 * Implements hook_library().
 * @return string
 */
function ak_cp_library() {
  $libraries['ak_cp'] = array(
    'title' => 'Ak community platform',
    'website' => '',
    'version' => '1.0',
    'js' => array(
       drupal_get_path('module', 'ak_cp') . '/js/underscore-min.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/leaflet_dvf/dist/leaflet-dvf.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/leaflet_google_places_autocomplete/src/js/leaflet-gplaces-autocomplete.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/leaflet_search/src/leaflet-search.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/Leaflet.zoomslider/src/L.Control.Zoomslider.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/bootstrap_select/js/bootstrap-select.js' => array(),
       ),
   
    'css' => array(
      drupal_get_path('module', 'ak_cp') . '/js/leaflet_dvf/dist/css/dvf.css' => array(),
      drupal_get_path('module', 'ak_cp') . '/js/leaflet_google_places_autocomplete/dist/css/leaflet-gplaces-autocomplete.css' => array(),
      drupal_get_path('module', 'ak_cp') . '/js/leaflet_search/src/leaflet-search.css' => array(),
      drupal_get_path('module', 'ak_cp') . '/js/Leaflet.zoomslider/src/L.Control.Zoomslider.css' => array(),
      drupal_get_path('module', 'ak_cp') . '/js/bootstrap_select/css/bootstrap-select.css' => array(),
      ),
    
  );

  return $libraries;
}

/**
 * Implements hook_js_alter()
 * Fix owl slider scripts sequence
 */
function  ak_cp_js_alter(&$javascript) {
  foreach ($javascript as $key => $value) {
    if(strpos($key, 'owl') !== false) {
      $javascript[$key]['scope'] = 'header'; 
    }
  }
}