<?php

/**
 * Implements hook_init().
 * @return string
 */

function ak_cp_init() {
 $openharvest_style = array(
        'openharvest-modal-style-fixed' => array(
          'modalSize' => array(
            'type' => 'fixed',
             'width' => 600,
             'height' => 450,
            // 'addWidth' => 0,
            // 'addHeight' => 20,
            // 'contentRight' => 0,
            // 'contentBottom' => 0,
          ),
          'modalOptions' => array(
            'opacity' => .4,
            'background-color' => '#000',
          ),
          'animation' => 'fadeIn',
          'modalTheme' => 'openharvest_modal_fixed',
          // Customize the AJAX throbber like so:
          // This function assumes the images are inside the module directory's "images"
          // directory:
          // ctools_image_path($image, $module = 'ctools', $dir = 'images')
          // 'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'happy'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
          // 'closeImage' => theme('image', array('path' => ctools_image_path('modal-close.png', 'happy'), 'alt' => t('Close window'), 'title' => t('Close window'))),
        ),
        'openharvest-modal-style-scale' => array(
          'modalSize' => array(
            'type' => 'scale',
            // 'width' => 600,
            // 'height' => 450,
            // 'addWidth' => 0,
            // 'addHeight' => 20,
            // 'contentRight' => 0,
            // 'contentBottom' => 0,
          ),
          'modalOptions' => array(
            'opacity' => .4,
            'background-color' => '#000',
          ),
          'animation' => 'fadeIn',
          'modalTheme' => 'openharvest_modal_scale',
          // Customize the AJAX throbber like so:
          // This function assumes the images are inside the module directory's "images"
          // directory:
          // ctools_image_path($image, $module = 'ctools', $dir = 'images')
          // 'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'happy'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
          // 'closeImage' => theme('image', array('path' => ctools_image_path('modal-close.png', 'happy'), 'alt' => t('Close window'), 'title' => t('Close window'))),
        ),
    );
    // Add the settings array defined above to Drupal 7's JS settings:
    drupal_add_js($openharvest_style, 'setting');
    // The function below assumes the happy.js file resides in [module_dir]/js
    ctools_add_js('openharvest_modal', 'ak_cp');
    // The function below assumes the happy.css file resides in [module_dir]/css
    ctools_add_css('openharvest_modal', 'ak_cp');
}

/**
 * Implements hook_library().
 * @return string
 */
function ak_cp_library() {
  $libraries['ak_cp'] = array(
    'title' => 'Ak community platform',
    'website' => '',
    'version' => '1.0',
    'js' => array(
       drupal_get_path('module', 'ak_cp') . '/js/underscore-min.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/leaflet_dvf/dist/leaflet-dvf.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/leaflet_google_places_autocomplete/src/js/leaflet-gplaces-autocomplete.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/leaflet_search/src/leaflet-search.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/Leaflet.zoomslider/src/L.Control.Zoomslider.js' => array(),
       drupal_get_path('module', 'ak_cp') . '/js/bootstrap_select/js/bootstrap-select.js' => array(),
       ),
   
    'css' => array(
      drupal_get_path('module', 'ak_cp') . '/js/leaflet_dvf/dist/css/dvf.css' => array(),
      drupal_get_path('module', 'ak_cp') . '/js/leaflet_google_places_autocomplete/dist/css/leaflet-gplaces-autocomplete.css' => array(),
      drupal_get_path('module', 'ak_cp') . '/js/leaflet_search/src/leaflet-search.css' => array(),
      drupal_get_path('module', 'ak_cp') . '/js/Leaflet.zoomslider/src/L.Control.Zoomslider.css' => array(),
      drupal_get_path('module', 'ak_cp') . '/js/bootstrap_select/css/bootstrap-select.css' => array(),
      ),
    
  );

  return $libraries;
}

/**
 * Implements hook_js_alter()
 * Fix owl slider scripts sequence
 */
function  ak_cp_js_alter(&$javascript) {
  foreach ($javascript as $key => $value) {
    if(strpos($key, 'owl') !== false) {
      $javascript[$key]['scope'] = 'header'; 
    }
  }
}



function ak_cp_preprocess_node(&$vars) {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['node']->type . '__' . $vars['view_mode'];
}